// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Identity struct {
	Provider string `json:"provider"`
	Codename string `json:"codename"`
}

type Kubernetes struct {
	APIURL  string `json:"apiUrl"`
	AuthURL string `json:"authUrl"`
	CaCert  string `json:"caCert"`
}
