version: 2.1

orbs:
  architect: giantswarm/architect@5.13.0

workflows:
  test:
    jobs:
    - architect/go-build:
        name: go-build
        binary: athena
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        requires:
        - go-build
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        context: architect
        name: push-athena-to-control-plane-app-catalog
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: athena
        executor: app-build-suite
        persist_chart_archive: true
          # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
        requires:
        - push-to-registries
    - architect/push-to-app-collection:
        name: push-athena-to-aws-app-collection
        context: architect
        app_name: athena
        app_collection_repo: aws-app-collection
        requires:
        - push-athena-to-control-plane-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        name: push-athena-to-azure-app-collection
        context: architect
        app_name: athena
        app_collection_repo: azure-app-collection
        requires:
        - push-athena-to-control-plane-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        name: push-athena-to-capa-app-collection
        context: architect
        app_name: athena
        app_collection_repo: capa-app-collection
        requires:
        - push-athena-to-control-plane-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        name: push-athena-to-vsphere-app-collection
        context: architect
        app_name: athena
        app_collection_repo: vsphere-app-collection
        requires:
        - push-athena-to-control-plane-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-catalog:
        context: architect
        name: push-athena-to-giantswarm-catalog
        app_catalog: giantswarm-catalog
        app_catalog_test: giantswarm-test-catalog
        chart: athena
        executor: app-build-suite
          # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
        requires:
        - push-to-registries
    - architect/run-tests-with-ats:
        name: execute chart tests
        filters:
            # Do not trigger the job on merge to main.
          branches:
            ignore:
            - main
        requires:
        - push-athena-to-control-plane-app-catalog


    - architect/push-to-app-collection:
        context: architect
        name: push-to-cloud-director-app-collection
        app_name: athena
        app_collection_repo: cloud-director-app-collection
        requires:
        - push-athena-to-control-plane-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-capa-app-collection
        app_name: athena
        app_collection_repo: capa-app-collection
        requires:
        - push-athena-to-control-plane-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-gcp-app-collection
        app_name: athena
        app_collection_repo: gcp-app-collection
        requires:
        - push-athena-to-control-plane-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-kvm-app-collection
        app_name: athena
        app_collection_repo: kvm-app-collection
        requires:
        - push-athena-to-control-plane-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
    - architect/push-to-app-collection:
        context: architect
        name: push-to-capz-app-collection
        app_name: athena
        app_collection_repo: capz-app-collection
        requires:
        - push-athena-to-control-plane-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/

    - architect/push-to-app-collection:
        context: architect
        name: push-to-proxmox-app-collection
        app_name: athena
        app_collection_repo: proxmox-app-collection
        requires:
        - push-athena-to-control-plane-app-catalog
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
