version: 2.1

orbs:
  architect: giantswarm/architect@4.24.0

workflows:
  test:
    jobs:
      - architect/go-build:
          name: go-build
          binary: athena
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-athena-to-quay
          context: architect
          image: "quay.io/giantswarm/athena"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-athena-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/athena"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-athena-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "athena"
          executor: "app-build-suite"
          persist_chart_archive: true
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
          requires:
            - push-athena-to-quay

      - architect/push-to-app-collection:
          name: push-athena-to-shared-app-collection
          context: architect
          app_name: "athena"
          app_collection_repo: "shared-app-collection"
          requires:
            - push-athena-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-athena-to-aws-app-collection
          context: architect
          app_name: "athena"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-athena-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-athena-to-azure-app-collection
          context: architect
          app_name: "athena"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-athena-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-athena-to-capa-app-collection
          context: architect
          app_name: "athena"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-athena-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-athena-to-vsphere-app-collection
          context: architect
          app_name: "athena"
          app_collection_repo: "vsphere-app-collection"
          requires:
            - push-athena-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-athena-to-giantswarm-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "athena"
          executor: "app-build-suite"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
          requires:
            - push-athena-to-quay

      - architect/run-tests-with-ats:
          name: execute chart tests
          filters:
            # Do not trigger the job on merge to main.
            branches:
              ignore:
                - main
          requires:
            - push-athena-to-control-plane-app-catalog


      - architect/push-to-app-collection:
          context: architect
          name: push-to-cloud-director-app-collection
          app_name: "athena"
          app_collection_repo: cloud-director-app-collection
          requires:
            - push-athena-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "athena"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-athena-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/


      - architect/push-to-app-collection:
          context: architect
          name: push-to-openstack-app-collection
          app_name: "athena"
          app_collection_repo: "capa-openstack-collection"
          requires:
            - push-athena-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

