{{- if and (not .Values.services.athena.letsencrypt) .Release.IsUpgrade .Values.fixJob.enabled }}
  {{- if .Capabilities.APIVersions.Has "cilium.io/v2" }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "athena.fixJob" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-7"
    {{- include "athena.fixJobAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "athena.fixJob" . | quote }}
    {{- include "athena.fixJobSelectorLabels" . | nindent 4 }}
    role: {{ include "athena.fixJobSelector" . | quote }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: {{ include "athena.fixJob" . | quote }}
      {{- include "athena.fixJobSelectorLabels" . | nindent 6 }}
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
        - ports:
            - port: "6443"
  {{- else}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "athena.fixJob" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-7"
    {{- include "athena.fixJobAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "athena.fixJob" . | quote }}
    {{- include "athena.fixJobSelectorLabels" . | nindent 4 }}
    role: {{ include "athena.fixJobSelector" . | quote }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: {{ include "athena.fixJob" . | quote }}
      {{- include "athena.fixJobSelectorLabels" . | nindent 6 }}
  # allow egress traffic to the Kubernetes API
  egress:
  - ports:
    - port: 443
      protocol: TCP
    # legacy port kept for compatibility
    - port: 6443
      protocol: TCP
    to:
    {{- range tuple "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" "100.64.0.0/10" }}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
  # deny ingress traffic
  ingress: []
  policyTypes:
  - Egress
  - Ingress
  {{- end }}
{{- end }}
