package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/giantswarm/athena/pkg/graph/exec"
	"github.com/giantswarm/athena/pkg/graph/model"
)

// Identity is the resolver for the identity field.
func (r *queryResolver) Identity(ctx context.Context) (*model.Identity, error) {
	i := &model.Identity{
		Provider: r.installationProvider,
		Codename: r.installationCodename,
	}

	return i, nil
}

// Query returns exec.QueryResolver implementation.
func (r *Resolver) Query() exec.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
