{{- if not .Values.services.athena.letsencrypt }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: "{{ .Values.name }}-certs-secret"
  namespace: {{ .Release.Namespace }}
labels:
  {{- include "athena.labels.common" . | nindent 2 }}
data:
  tls.crt: {{ .Values.ingress.tls.crtPemB64 | quote }}
  tls.key: {{ .Values.ingress.tls.keyPemB64 | quote }}
{{- end }}
