apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Values.name }}-certs-secret"
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.CrtPem | b64enc | quote }}
  tls.key: {{ .Values.Installation.V1.Secret.Certificate.GiantSwarm.KeyPem | b64enc | quote }}
