{{- if not .Values.services.athena.letsencrypt }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Values.name }}-certs-secret"
  namespace: {{ .Release.Namespace }}
labels:
  app: {{ .Values.name }}
data:
  tls.crt: {{ .Values.ingress.tls.crtPemB64 | quote }}
  tls.key: {{ .Values.ingress.tls.crtPemB64 | quote }}
{{- end }}
