apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-configmap"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
data:
  config.yaml: |
    server:
      allowedOrigins:
      - "{{ .Values.Installation.V1.GiantSwarm.Happa.Address }}"
      listenAddress: "0.0.0.0:8000"
    identity:
      provider: "{{ .Values.Installation.V1.Provider.Kind }}"
      codename: "{{ .Values.Installation.V1.Name }}"
    kubernetes:
      apiUrl: "{{ .Values.Installation.V1.Kubernetes.API.Address }}"
      authUrl: "{{ .Values.Installation.V1.GiantSwarm.OIDC.IssuerAddress }}"
      caCert: "{{ toYaml .Values.Installation.V1.Secret.Kubernetes.CAPem | indent 8 }}"
