apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-configmap"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
data:
  config.yaml: |
    server:
      allowedOrigins:
      - "{{ .Values.services.happa.address }}"
      listenAddress: "0.0.0.0:8000"
    identity:
      provider: "{{ .Values.provider.kind }}"
      codename: "{{ .Values.managementCluster.name }}"
    kubernetes:
      apiUrl: "{{ .Values.kubernetes.api.address }}"
      authUrl: "{{ .Values.oidc.issuerAddress }}"
      caCert: "{{ toYaml .Values.kubernetes.caPem | indent 8 }}"
    {{- if .Values.provider.availabilityZones }}
    capabilities:
      availabilityZones:
      {{- range .Values.provider.availabilityZones }}
      - {{ . | quote }}
      {{- end }}
    {{- end }}
