apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-configmap"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "athena.labels.common" . | nindent 4 }}
data:
  config.yaml: |
    server:
      allowedOrigins:
      - "{{ .Values.services.happa.address }}"
      listenAddress: "0.0.0.0:8000"
    identity:
      {{- if (eq (kindOf .Values.provider) "string") }}
      provider: "{{ .Values.provider }}"
      {{- else }}
      provider: "{{ .Values.provider.kind }}"
      {{- end }}
      {{- if and (eq (kindOf .Values.managementCluster) "string") (.Values.clusterID) }}
      codename: "{{ .Values.managementCluster }}-{{ .Values.clusterID }}"
      {{- else if (eq (kindOf .Values.managementCluster) "string") }}
      codename: "{{ .Values.managementCluster }}"
      {{- else if .Values.clusterID }}
      codename: "{{ .Values.managementCluster.name }}-{{ .Values.clusterID }}"
      {{- else }}
      codename: "{{ .Values.managementCluster.name }}"
      {{- end }}
    kubernetes:
      {{- if .Values.kubernetes.api.address }}
      apiUrl: "{{ .Values.kubernetes.api.address }}"
      {{- else }}
      apiUrl: "https://api.{{ .Values.baseDomain }}"
      {{- end }}
      {{- if .Values.oidc.issuerAddress }}
      authUrl: "{{ .Values.oidc.issuerAddress }}"
      {{- else }}
      authUrl: "https://dex.{{ .Values.baseDomain }}"
      {{- end }}
      {{- if .Values.kubernetes.caPem }}
      caCert: "{{ toYaml .Values.kubernetes.caPem | indent 8 }}"
      {{- else if .Values.clusterCA }}
      caCert: "{{ toYaml .Values.clusterCA | replace "|-" "|" | indent 8 }}"
      {{- end }}
    analytics:
      environmentType: {{ .Values.environmentType}}
