apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 2
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
    spec:
      volumes:
      - name: "{{ .Values.name }}-configmap"
        configMap:
          name: "{{ .Values.name }}-configmap"
          items:
          - key: config.yaml
            path: config.yaml
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      containers:
      - name: {{ .Values.image.name }}
        image: "{{ .Values.registry.domain }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        args:
        - "daemon"
        - "--config-dir=/var/run/athena/configmap/"
        - "--config-file=config"
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 30Mi
          limits:
            cpu: 250m
            memory: 250Mi
        volumeMounts:
        - name: "{{ .Values.name }}-configmap"
          mountPath: /var/run/athena/configmap/
          readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 1
      imagePullSecrets:
      - name: "{{ .Values.name }}-pull-secret"
      serviceAccountName: {{ .Values.name }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - {{ .Values.name }}
              topologyKey: kubernetes.io/hostname
