apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Values.name }}-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
stringData:
  secret.yaml: |
    analytics:
      credentialsJSON: {{ .Values.secret.firestoreServiceAccountKey | toJson }}
