apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Values.name }}-secret"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "athena.labels.common" . | nindent 4 }}
stringData:
  secret.yaml: |
    analytics:
      credentialsJSON: {{ .Values.secret.firestoreServiceAccountKey | toJson }}
