kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}
  labels:
    {{- include "athena.labels.common" . | nindent 4 }}
spec:
  ports:
  - port: 8000
    targetPort: http
  selector:
    app: {{ .Values.name }}
